#!/bin/bash

##TODO -- build this as a package
## this is just a helper for now

set -e

MYUSER=cif
MYGROUP=cif

if [ `whoami` != 'root' ]; then
    echo 'this script must be run as root'
    exit 0
fi

apt-get update
apt-get install -qq python-software-properties
echo "yes" | sudo add-apt-repository "ppa:chris-lea/zeromq"
wget -O - http://packages.elasticsearch.org/GPG-KEY-elasticsearch | apt-key add -

if [ -f /etc/apt/sources.list.d/elasticsearch.list ]; then
    echo "sources.list.d/elasticsearch.list already exists, skipping..."
else
    echo "deb http://packages.elasticsearch.org/elasticsearch/1.0/debian stable main" >> /etc/apt/sources.list.d/elasticsearch.list
fi

apt-get update
apt-get install -y elasticsearch apache2 libapache2-mod-perl2 curl mailutils build-essential git-core automake cpanminus rng-tools openjdk-7-jre-headless libtool pkg-config vim htop bind9 libzmq3-dev libffi6 libmoose-perl libmouse-perl libanyevent-perl liblwp-protocol-https-perl libxml2-dev libexpat-dev nginx libgeoip-dev geoip-bin

echo 'HRNGDEVICE=/dev/urandom' >> /etc/default/rng-tools
service rng-tools restart

if [ -z `grep -l 'spamhaus.org' /etc/bind/named.conf.local` ]; then
    cat ./named.conf.local >> /etc/bind/named.conf.local
fi

service bind9 restart

if [ -z `grep -l '127.0.0.1' /etc/resolvconf/resolv.conf.d/base` ]; then
    echo 'adding 127.0.0.1 as nameserver'
    echo "nameserver 127.0.0.1" >> /etc/resolvconf/resolv.conf.d/base
    echo "restarting network..."
    ifdown eth0 && sudo ifup eth0
fi

if [ -z `getent passwd $MYUSER` ]; then
	echo "adding user: $MYUSER"
	useradd $MYUSER -m -s /bin/bash
	adduser www-data $MYUSER
fi

if [ ! -f /home/cif/.profile ]; then
	touch /home/cif/.profile
fi

if [ -z `grep -l '/opt/cif/bin' /home/cif/.profile` ]; then
    MYPROFILE=/home/$MYUSER/.profile
    echo "" >> $MYPROFILE
    echo "# automatically generated by CIF installation" >> $MYPROFILE
    echo 'PATH=/opt/cif/bin:$PATH' >> $MYPROFILE
fi

echo 'copying init.d scripts...'
cp ../../packaging/debian/init.d/cif-smrt /etc/init.d/
cp ../../packaging/debian/init.d/cif-router /etc/init.d/

if [ ! -f /etc/default/cif ]; then
    echo 'setting /etc/default/cif'
    cp ../../packaging/debian/default/cif /etc/default/cif
fi

update-rc.d elasticsearch defaults 95 10
update-rc.d cif-router defaults 95 10
update-rc.d cif-smrt defaults 95 10
